name: Make & release GeoJSON

on:
  push:

jobs:
  do-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: cicd-tests
    steps:
      - name: Checkout Git submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run "make_geojson.py"
        run: python make_geojson.py

      - name: Test if if worked
        run: ls -la output/

      - name: Check output existence
        uses: thebinaryfelix/check-file-existence-action@v1
        with:
          files: 'output/airports_full_all_feet.geojson, output/airports_full_all_meter.geojson'
