name: Make & release KML & GeoJSON

on:
  push:
    branches:
      - master
      - dev-kml

jobs:
  do-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: cicd-tests
    steps:
      - name: Checkout Git submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installing dependencies
        run: pip install -r requirements.txt

      - name: Run "make_all.py"
        run: python make_all.py

      - name: Check output existence
        uses: thebinaryfelix/check-file-existence-action@1.0.0
        with:
          files: 'output/airports_full_all_feet.geojson, output/airports_full_all_meter.geojson, output/airports_full.kml'

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release for ${{ github.ref_name }} @ ${{ github.sha }}
          body: |
            Automatic update release made through GitHub Actions.
          draft: true
          prerelease: false

      - name: Upload asset `airports_full_all_feet.geojson`
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/airports_full_all_feet.geojson
          asset_name: airports_full_all_feet.geojson
          asset_content_type: application/geo+json

      - name: Upload asset `airports_full_all_meter.geojson`
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/airports_full_all_meter.geojson
          asset_name: airports_full_all_meter.geojson
          asset_content_type: application/geo+json

      - name: Upload asset `airports_full.kml`
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/airports_full.kml
          asset_name: airports_full.kml
          asset_content_type: application/vnd.google-earth.kml+xml
